### PR TITLE
updated with hello in 10 main languages

### PR DESCRIPTION
**Pull request by alansmathew**
thought this will be cool

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Nice idea, thank you 👍

**Comment by adityaraute** [comment]
How can conflicts be resolved here?

**Comment by eddiejaoude** [comment]
Thank you @adityaraute for the nudge 👍 , I have resolved the conflicts

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
