### PR TITLE
✨ added contribution graph

### PR DESCRIPTION
**Pull request by adityatheoctocatdev**
Screenshot 2021-05-04 at 3 31 25 PM

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the contribution. I might remove some parts first, otherwise the whole customised section is too long

**Comment by roto93** [comment]
@adityatheoctocatdev This graph is sooo cool. I didn't realize there is a way to do this.

**Comment by khushalbhardwaj-0111** [comment]
More than anything you must add your GitHub trophies to the profile readme, yours are insane 🤯.
Trophies

**Comment by eddiejaoude** [comment]
Thanks for the contribution, I am reducing the graphs at the moment, to keep my profile more concise

**Pull request closed without merging**
