### PR TITLE
Fixed the naming and naming convention

### PR DESCRIPTION
**Pull request by abughurab16**
Sorry i Had to re-send  a fork the previous one wouldn't allow me to edit the file name and i dont know how to do it manually on github.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you 👍 , but the old file will need to be removed, otherwise 2 of the same actions will run

**Comment by adityaraute** [comment]
Delete the previous file in your fork.

**Comment by krishdevdb** [comment]
@eddiejaoude the pull request fork has been deleted, maybe close this pull request?

**Comment by eddiejaoude** [comment]
The patch still exists, so it could be merged, however I have now removed this GitHub action from the repo. So yes we should close it 👍 . Thanks @krishdevdb 

thank you @abughurab16 for the PR

**Pull request closed without merging**
