### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pulkit0076**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the PR. The trophys are not something I am keen on having at the moment. You still get your green square though for creating the PR 🟩

**Comment by Pulkit0076** [comment]
Ok sir but even there is an edit at the GitHub stats please do check it once

**Comment by Pulkit0076** [comment]
And even I have added a profile views badge in the last of it so just let me know how is it and would like to add it

**Comment by eddiejaoude** [comment]
The PR has many changes, it is easier to review, discuss and accept when a PR is small and does 1 thing not many

**Pull request closed without merging**
