### PR TITLE
Added Programming Languages stats

### PR DESCRIPTION
**Pull request by ShoaibKakal**
- [x] Read Github Community Guidelines.

- People might want to know which programming language you work on the most so I added a view that does the exact same thing. 

- It shows the top 5 programming languages you use in your repositories.

- Link to your languages stats `https://github-readme-stats.vercel.app/api/top-langs/?username=eddiejaoude&count_private=true`
Eddie stats

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the great pull request 👍 

Btw your GitHub profile looks awesome, you should add it to our repo of awesome GitHub profiles http://github.com/EddieJaoudeCommunity/awesome-github-profiles

**Comment by Shoaibpython** [comment]
Welcome and Thank you for such awesome profiles suggestions.

**Comment by dumbcoder7** [comment]
Sorry, but I am new to this. Has this Pull Request not been merged yet? It seems to be a very important addition and the owner has also appreciated it.

**Comment by ShoaibKakal** [comment]
Yes, this pull request not been merged yet. Eddie liked my pull request but he doesn't want to populate his README.md anymore.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
Sorry @ShoaibKakal , it slipped through the cracks. Thank you @dumbcoder7 for the nudge 👍

**Comment by dumbcoder7** [comment]
Always with the nudges here

**Pull request merged**
