### PR TITLE
Added some sample testimonial sections

### PR DESCRIPTION
**Pull request by dumbcoder7**
Related to the Issue #5 

I have presented three different styles for the Testimonials section. Sadly, I am not satisfied with any as I am not able to embed adequate CSS in markdown. Hence marking the PR as draft. Will try to incorporate changes if you have any.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Oh wow great options 👍 . Here are my thoughts...

Although style 3 looks very cool, it will take up a lot more space. So I am thinking style 2 might be a winning 🤓 . What do you think?

**Comment by dumbcoder7** [comment]
> Oh wow great options 👍 . Here are my thoughts...
> 
> Although style 3 looks very cool, it will take up a lot more space. So I am thinking style 2 might be a winning 🤓 . What do you think?

I agree. Style 3 takes up a lot of space. Sadly, there is no way to reduce the space and make it look good. Will confirm style 2 now.

**Comment by eddiejaoude** [comment]
This looks great 👍 

I wonder about the big "closing" quote, I feel there should be an opening one too 🤔

**Comment by dumbcoder7** [comment]
_Original_ 
<p align = "center">
<h4 align="center">Testimonials <br><h1 align = "center">❞</h1></h4>  
</p>


_Choice 1_
<p align = "center">
<h4 align="center">Testimonials <br><h1 align = "center">❝❞</h1></h4>  
</p>

_Choice 2_
<p align = "center">
<h4 align="center"><b>❝</b> Testimonials <b>❞</b></h4>  
</p>


_Choice 3_
<p align = "center">
<h4 align="center">Testimonials <br><h1 align = "center">❝</h1></h4>  
</p>


_Choice 4_
<p align = "center">
<h4 align="center">Testimonials <br><h1 align = "center">❝</h1></h4>  
</p>

<p align = "center">
<table align = "center" >
  <tr>
  <th>Author</th>
  <th>Message</th>
  </tr>
  <tr>
  <td>Testimonial Body 1</td>
  <td>Author 1</td>
  </tr>
  <tr>
  <td>Testimonial Body 2</td>
  <td>Author 2</td>
  </tr>
  <tr>
  <td>Testimonial Body 3</td>
  <td>Author 3</td>
  </tr>
</table>
</p>

<p align = "center">
<h1 align = "center">❞</h1>
</p>



<hr>

Have your pick!

My vote goes for either the Original or Choice 3.

**Comment by eddiejaoude** [comment]
wow looks great 👍 

Choice 4 I think is my favourite 😍

**Comment by dumbcoder7** [comment]
Updated accordingly!

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍 . Thank you 🤓

**Comment by eddiejaoude** [comment]
Screenshot 2021-01-06 at 13 12 00

**Comment by dumbcoder7** [comment]
Now we need to add actual Testimonials in there 😂

**Comment by eddiejaoude** [comment]
lol yes 👍 - I added a few just now. I will add more soon 🤓

**Comment by dumbcoder7** [comment]
Wait, testimonials meant tweets? Well then we could simply embed them [thus](https://keitaito.com/blog/2017/01/20/embedding-tweets-in-github-pages.html) 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Check out my iOS game, High5! <a href="https://t.co/QZEKLg3G2i">https://t.co/QZEKLg3G2i</a></p>&mdash; Hjonkeita Itonk hjonk hjonk (@keitaitok) <a href="https://twitter.com/keitaitok/status/504110217940836353?ref_src=twsrc%5Etfw">August 26, 2014</a></blockquote>

**Comment by eddiejaoude** [comment]
I could not get it to work, it was removed by GitHub when rendered. Also I am not sure if it will take up too much space when I have say 10+?

**Comment by dumbcoder7** [comment]
Yes, true it will. But maybe screenshots of those tweets can work? I don't know. 
I assumed Testimonials to be an official appreciation from your clients or colleagues.

**Comment by eddiejaoude** [comment]
I used to do official testimonials, but I feel them to be less authentic. I now collect some (when I remember), links from twitter

**Comment by dumbcoder7** [comment]
Alright, cool

**Pull request merged**
